"""initial schema

Revision ID: 3d37a654124e
Revises: 
Create Date: 2026-09-21 11:52:01.988111
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d37a654124e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('sender_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('corrected_labels', sa.JSON(), nullable=False),
    sa.Column('probabilities', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corrections_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corrections_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('google_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False),
    sa.Column('history_id', sa.String(length=64), nullable=True),
    sa.Column('watch_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_accounts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('gmail_label_id', sa.String(length=128), nullable=True),
    sa.Column('parent', sa.String(length=128), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_label_tenant_name')
    )
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labels_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer_type', sa.String(length=32), nullable=False),
    sa.Column('allowed_answers', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_question_tenant_key')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('match_mode', sa.String(length=8), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('stop_processing', sa.Boolean(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('is_system_protected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ruleset_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('author_email', sa.String(length=320), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ruleset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ruleset_versions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sender_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_list_tenant_name')
    )
    with op.batch_alter_table('sender_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sender_lists_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('triage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sender_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('applied_labels', sa.JSON(), nullable=False),
    sa.Column('matched_rule_key', sa.String(length=64), nullable=True),
    sa.Column('ruleset_version', sa.Integer(), nullable=True),
    sa.Column('probabilities', sa.JSON(), nullable=False),
    sa.Column('classifier_name', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'message_id', name='uq_triage_tenant_message')
    )
    with op.batch_alter_table('triage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triage_records_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triage_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('triage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triage_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_triage_records_message_id'))

    op.drop_table('triage_records')
    with op.batch_alter_table('sender_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sender_lists_tenant_id'))

    op.drop_table('sender_lists')
    with op.batch_alter_table('ruleset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ruleset_versions_tenant_id'))

    op.drop_table('ruleset_versions')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_tenant_id'))

    op.drop_table('rules')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_tenant_id'))

    op.drop_table('questions')
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labels_tenant_id'))

    op.drop_table('labels')
    with op.batch_alter_table('google_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_accounts_tenant_id'))

    op.drop_table('google_accounts')
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corrections_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_corrections_message_id'))

    op.drop_table('corrections')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))

    op.drop_table('audit_logs')
    op.drop_table('tenants')
    # ### end Alembic commands ###
